#pragma once
#include "handler.hpp"
#include <vector>

namespace ty::globals
{
	static handler handler;

	static const size_t blacklisted_dlls_length = 477;
	static const wchar_t* blacklisted_dlls[] = {
		L"truetransparencyhook.dll", L"nmas.dll", L"nmas.dll", L"mstscax.dll", L"ncjpeg.dll", L"nchooks.dll", L"ncjpeg.dll",
		L"ncjpeg.dll", L"nchooks.dll", L"nchooks.dll", L"nchooks.dll", L"vnchooks.dll", L"vnchooks.dll", L"vnchooks.dll",
		L"fwcontrol.dll", L"rntfywnd.dll", L"altdesk.dll", L"cvdh120.dll", L"cdhook.dll", L"dphooks.dll",
		L"component_2000.dll", L"fdhooks.dll", L"gsres.dll", L"dkset.dll", L"mud2004.dll", L"kauth.dll", L"kauth.dll",
		L"msvdm.dll", L"spaceglu.dll", L"ultramon.dll", L"ultramon.dll", L"imappservice.dll", L"import_everybuddy.dll",
		L"gabberlib.dll", L"gaim.dll", L"icqliteshell.dll", L"webchat.dll", L"imlib.dll", L"imlib.dll", L"imlib.dll",
		L"webchat.dll", L"useridletracker.dll", L"igc_client.dll", L"jmutils.dll", L"idlehook.dll", L"idlehook.dll",
		L"msgslang.dll", L"myjabberclient.dll", L"neosappmodule.dll", L"imclient.dll", L"palsound.dll", L"pidgin.dll",
		L"jabberclient.dll", L"tipic.dll", L"timessenger.dll", L"trillian.dll", L"idlehooks.dll", L"winmsres.dll",
		L"yabberxml.dll", L"myyahoo.dll", L"auvisres.dll", L"vycres.dll", L"vmres.dll", L"jabber-net.dll", L"libsim-0.dll",
		L"rivalsockets.dll", L"scap2000.dll", L"asr100.dll", L"asr200.dll", L"flashbackinstall.dll", L"fbplayerapi.dll",
		L"camtasiafilters.dll", L"camtasiafilters.dll", L"camtasiafilters.dll", L"captivateutils.dll", L"kcs41276.dll",
		L"swmpf472.dll", L"kcs41276.dll", L"ck8212drv.dll", L"ck8212drv.dll", L"ck8212drv.dll", L"cs6213drv.dll",
		L"ck8212drv.dll", L"hooksmfcdll.dll", L"dsconverter1033.dll", L"dcmanager.dll", L"npdivx32.dll",
		L"drdivxcontrols.dll", L"dpugui10.dll", L"drdivxcontrols.dll", L"capscrn.dll", L"sedit_en.dll", L"capdll.dll",
		L"mclick2.dll", L"jingengine.dll", L"wmenceng.dll", L"wmenceng.dll", L"streameditor.dll", L"dsregmsrp.dll",
		L"wincamswf.dll", L"wincamswf.dll", L"scap001s.dll", L"scap001p.dll", L"anydx.dll", L"ectntcap.dll", L"qcaphk.dll",
		L"cp6hooks.dll", L"cze32img.dll", L"czp32img.dll", L"capthumb.dll", L"flinterf.dll", L"fsdlg.dll", L"hardcopy pro.dll",
		L"hoverkhook.dll", L"hprres6.dll", L"paint shop prorc.dll", L"paint shop prorc.dll", L"paint shop prorc.dll",
		L"hprres.dll", L"sendatt.dll", L"ssm.dll", L"sh4plus.dll", L"sh420.dll", L"capturelib.dll", L"smartcapture.dll",
		L"snagitres.dll", L"snagitieaddin.dll", L"snagitshellext.dll", L"ectntcap.dll", L"winkdll.dll", L"wpcap.dll",
		L"netbee.dll", L"awptac.dll", L"capsares.dll", L"cstsv.dll", L"cv2k.dll", L"cv2k.dll", L"dstnct32.dll", L"dnmsniff.dll",
		L"libethereal.dll", L"peek.dll", L"ipmasterwincap.dll", L"ipmasterwincap.dll", L"ecapn.dll", L"indis.dll",
		L"nmsupp.dll", L"netwib534.dll", L"probedll.dll", L"probeconfig.dll", L"probeconfig.dll", L"pvcapt.dll",
		L"sfmxplib.dll", L"libnetnt.dll", L"wntch32.dll", L"sstexp32.dll", L"sstexp32.dll", L"sstexp32.dll", L"usft_ext.dll",
		L"usft_ext.dll", L"usnfusru.dll", L"iewatch.dll", L"logexp.dll", L"alaware.dll", L"logexp.dll", L"swkbhk.dll",
		L"applog.dll", L"inetlog.dll", L"keylogger.dll", L"screenlog.dll", L"soundlog.dll", L"gdh.dll", L"gdh.dll",
		L"serversnapshot.dll", L"appcommon.dll", L"appcommon.dll", L"ikeyhk2.dll", L"klphks.dll", L"nomod32.dll",
		L"nomod32.dll", L"survservices.dll", L"sstexp32.dll", L"syswms32.dll", L"qlib.dll", L"qlib.dll", L"qutils.dll",
		L"hlib32.dll", L"hlib32.dll", L"hlib32.dll", L"keyspy.dll", L"appspy.dll", L"keyspy.dll", L"amcontrol.dll",
		L"mmcndmgr.dll", L"ureg.dll", L"rrsec.dll", L"rrsec.dll", L"regxplor.dll", L"winutil4.dll", L"rrshell.dll", L"lbsu.dll",
		L"regweb.dll", L"epreg.dll", L"wcwin.dll", L"wcwcr.dll", L"wcwin.dll", L"issutil.dll", L"wcwin.dll", L"winroll.dll",
		L"vitridll.dll", L"twhook.dll", L"sys012k.dll", L"quick shell.dll", L"powermenuhook.dll", L"transdll.dll",
		L"hwhook.dll", L"ghosteffectshook.dll", L"asmemb.dll", L"aimemb.dll", L"atwemb.dll", L"atbemb.dll", L"astrans.dll",
		L"ybskin2.dll", L"callcont.dll", L"lmcdata.dll", L"checkservers.dll", L"trillian.dll", L"hvdi.dll",
		L"skypeieplugin.dll", L"roger.dll", L"ipcom.dll", L"cc_voip.dll", L"icqlsrp.dll", L"dpusipp.dll", L"ivapi.dll",
		L"aolsvcmgr.dll", L"winpindll.dll", L"rocketdock.dll", L"fraps.dll", L"truetransparencyhook.dll", L"nmas.dll",
		L"nmas.dll", L"mstscax.dll", L"ncjpeg.dll", L"nchooks.dll", L"ncjpeg.dll", L"ncjpeg.dll", L"nchooks.dll",
		L"nchooks.dll", L"nchooks.dll", L"vnchooks.dll", L"vnchooks.dll", L"vnchooks.dll", L"fwcontrol.dll", L"rntfywnd.dll",
		L"altdesk.dll", L"cvdh120.dll", L"cdhook.dll", L"dphooks.dll", L"component_2000.dll", L"fdhooks.dll", L"gsres.dll",
		L"dkset.dll", L"mud2004.dll", L"kauth.dll", L"kauth.dll", L"msvdm.dll", L"spaceglu.dll", L"ultramon.dll",
		L"ultramon.dll", L"imappservice.dll", L"import_everybuddy.dll", L"gabberlib.dll", L"gaim.dll", L"icqliteshell.dll",
		L"webchat.dll", L"imlib.dll", L"imlib.dll", L"imlib.dll", L"webchat.dll", L"useridletracker.dll", L"igc_client.dll",
		L"jmutils.dll", L"idlehook.dll", L"idlehook.dll", L"msgslang.dll", L"myjabberclient.dll", L"neosappmodule.dll",
		L"imclient.dll", L"palsound.dll", L"pidgin.dll", L"jabberclient.dll", L"tipic.dll", L"timessenger.dll",
		L"trillian.dll", L"idlehooks.dll", L"winmsres.dll", L"yabberxml.dll", L"myyahoo.dll", L"auvisres.dll", L"vycres.dll",
		L"vmres.dll", L"jabber-net.dll", L"libsim-0.dll", L"rivalsockets.dll", L"scap2000.dll", L"asr100.dll", L"asr200.dll",
		L"flashbackinstall.dll", L"fbplayerapi.dll", L"camtasiafilters.dll", L"camtasiafilters.dll", L"camtasiafilters.dll",
		L"captivateutils.dll", L"kcs41276.dll", L"swmpf472.dll", L"kcs41276.dll", L"ck8212drv.dll", L"ck8212drv.dll",
		L"ck8212drv.dll", L"cs6213drv.dll", L"ck8212drv.dll", L"hooksmfcdll.dll", L"dsconverter1033.dll", L"dcmanager.dll",
		L"npdivx32.dll", L"drdivxcontrols.dll", L"dpugui10.dll", L"drdivxcontrols.dll", L"fraps.dll", L"capscrn.dll",
		L"sedit_en.dll", L"capdll.dll", L"mclick2.dll", L"jingengine.dll", L"wmenceng.dll", L"wmenceng.dll",
		L"streameditor.dll", L"dsregmsrp.dll", L"wincamswf.dll", L"wincamswf.dll", L"scap001s.dll", L"scap001p.dll",
		L"anydx.dll", L"ectntcap.dll", L"qcaphk.dll", L"cp6hooks.dll", L"cze32img.dll", L"czp32img.dll", L"capthumb.dll",
		L"flinterf.dll", L"fsdlg.dll", L"hardcopy pro.dll", L"hoverkhook.dll", L"hprres6.dll", L"paint shop prorc.dll",
		L"paint shop prorc.dll", L"paint shop prorc.dll", L"hprres.dll", L"sendatt.dll", L"ssm.dll", L"sh4plus.dll",
		L"sh420.dll", L"capturelib.dll", L"smartcapture.dll", L"snagitres.dll", L"snagitieaddin.dll", L"snagitshellext.dll",
		L"ectntcap.dll", L"winkdll.dll", L"wpcap.dll", L"netbee.dll", L"awptac.dll", L"capsares.dll", L"cstsv.dll", L"cv2k.dll",
		L"cv2k.dll", L"dstnct32.dll", L"dnmsniff.dll", L"libethereal.dll", L"peek.dll", L"ipmasterwincap.dll",
		L"ipmasterwincap.dll", L"ecapn.dll", L"indis.dll", L"nmsupp.dll", L"netwib534.dll", L"probedll.dll",
		L"probeconfig.dll", L"probeconfig.dll", L"pvcapt.dll", L"sfmxplib.dll", L"libnetnt.dll", L"wntch32.dll",
		L"sstexp32.dll", L"sstexp32.dll", L"sstexp32.dll", L"usft_ext.dll", L"usft_ext.dll", L"usnfusru.dll", L"iewatch.dll",
		L"logexp.dll", L"alaware.dll", L"logexp.dll", L"swkbhk.dll", L"applog.dll", L"inetlog.dll", L"keylogger.dll",
		L"screenlog.dll", L"soundlog.dll", L"gdh.dll", L"gdh.dll", L"serversnapshot.dll", L"appcommon.dll", L"appcommon.dll",
		L"ikeyhk2.dll", L"klphks.dll", L"nomod32.dll", L"nomod32.dll", L"survservices.dll", L"sstexp32.dll", L"syswms32.dll",
		L"qlib.dll", L"qlib.dll", L"qutils.dll", L"hlib32.dll", L"hlib32.dll", L"hlib32.dll", L"keyspy.dll", L"appspy.dll",
		L"keyspy.dll", L"amcontrol.dll", L"mmcndmgr.dll", L"ureg.dll", L"rrsec.dll", L"rrsec.dll", L"regxplor.dll",
		L"winutil4.dll", L"rrshell.dll", L"lbsu.dll", L"regweb.dll", L"epreg.dll", L"wcwin.dll", L"wcwcr.dll", L"wcwin.dll",
		L"issutil.dll", L"wcwin.dll", L"winroll.dll", L"vitridll.dll", L"twhook.dll", L"sys012k.dll", L"quick shell.dll",
		L"powermenuhook.dll", L"transdll.dll", L"hwhook.dll", L"ghosteffectshook.dll", L"asmemb.dll", L"aimemb.dll",
		L"atwemb.dll", L"atbemb.dll", L"astrans.dll", L"ybskin2.dll", L"callcont.dll", L"lmcdata.dll", L"checkservers.dll",
		L"trillian.dll", L"hvdi.dll", L"skypeieplugin.dll", L"roger.dll", L"ipcom.dll", L"cc_voip.dll", L"icqlsrp.dll",
		L"dpusipp.dll", L"ivapi.dll", L"aolsvcmgr.dll", L"winpindll.dll", L"rocketdock.dll", L"fraps.dll"
	};

    static const wchar_t* blacklisted_exes[] = {
        L"livecomm.exe", L"twitter-win8.exe", L"hcontrol.exe", L"kem.exe", L"setpoint.exe", L"type32.exe",
        L"msmsgs.exe", L"msnmsgr.exe", L"wlcomm.exe", L"deskpins.exe", L"wwahost.exe", L"displayfusion.exe",
        L"displayfusionhookappwin6064.exe", L"displayfusionhookappwin6032.exe", L"displayfusionservice.exe", L"desktops.exe", L"synergy.exe", L"synergyc.exe",
        L"synergyd.exe", L"synergys.exe", L"taskmgr.exe", L"sidebar.exe", L"sidebar.exe", L"avgas.exe",
        L"smartboardtools.exe", L"smartboardservice.exe", L"glass2k.exe", L"truetransparency.exe", L"manycam.exe", L"magiccamera.exe",
        L"ctlvcentral3.exe", L"ctlvcentral2.exe", L"ctlvcentral.exe", L"webcamdell.exe", L"webcamdell2.exe", L"remoting_desktop.exe",
        L"remote_assistance_host.exe", L"remoting_native_messaging_host.exe", L"apc_admin.exe", L"apc_host.exe", L"apc_admin.exe", L"apc_host.exe",
        L"conf.exe", L"mnmsrvc.exe", L"mstsc.exe", L"netctl.exe", L"netctl.exe", L"netserv.exe",
        L"netserv.exe", L"ncscc.exe", L"ncscc.exe", L"netchat.exe", L"netchat.exe", L"vncviewer.exe",
        L"winvnc.exe", L"winvnc4.exe", L"vncviewer.exe", L"rcpserver.exe", L"rcpadmin.exe", L"rpaccess.exe",
        L"rpaccesshs.exe", L"actionsserver.exe", L"tvnserver.exe", L"tvnviewer.exe", L"vncviewer.exe", L"winvnc.exe",
        L"vncviewer.exe", L"winvnc.exe", L"vncviewer.exe", L"win2vnc.exe", L"sshdctrl.exe", L"winsshd.exe",
        L"keygen.exe", L"wissh.exe", L"g2svc.exe", L"g2comm.exe", L"g2tray.exe", L"g2pre.exe",
        L"logmein.exe", L"ramaint.exe", L"join.me.exe", L"logmein.exe", L"teamviewer.exe", L"teamviewer.exe",
        L"teamviewer.exe", L"romserver.exe", L"romserver.exe", L"rserver3.exe", L"rserver3.exe", L"igremote.exe",
        L"igremote.exe", L"rpcsetup.exe", L"rpcgrab.exe", L"rpcsetup.exe", L"crossloopconnect.exe", L"crossloopservice.exe",
        L"crossloopservice.exe", L"yuuguu.exe", L"srserver.exe", L"srservice.exe", L"srsoobe.exe", L"altdesk.exe",
        L"bosskey.exe", L"virtdesktop.exe", L"cdesk.exe", L"dp.exe", L"exedesk.exe", L"exedesk_wd.exe",
        L"goscreen.exe", L"litestep.exe", L"managedesk.exe", L"mud2004.exe", L"multidesk.exe", L"desktop.exe",
        L"pictowin.exe", L"talisman.exe", L"vern36.exe", L"vdtlbx.exe", L"kauths.exe", L"virtuawin.exe",
        L"winlist.exe", L"explorer.exe", L"winspace.exe", L"xdesk.exe", L"ultramon.exe", L"aceclient.exe",
        L"acemessage.exe", L"run.exe", L"aim6.exe", L"ayttm.exe", L"bitwise.exe", L"clique2.exe",
        L"exodus.exe", L"gabber.exe", L"gaim.exe", L"gajim.exe", L"gcn.exe", L"goim.exe",
        L"gush.exe", L"gushui.exe", L"hello.exe", L"icqlite.exe", L"igoinc~1.exe", L"messenger2.exe",
        L"im2wizard.exe", L"imvite.exe", L"ima.exe", L"imc.exe", L"ims.exe", L"instant.exe",
        L"messenger.exe", L"igc.exe", L"kava.exe", L"linq.exe", L"lluna.exe", L"maxxchat.exe",
        L"miranda32.exe", L"mirc.exe", L"msnmsgr.exe", L"myjabber.exe", L"neos.exe", L"officepopup.exe",
        L"paltalk.exe", L"pandion.exe", L"papla.exe", L"pidgin.exe", L"lync.exe", L"winvmaclient.exe",
        L"psi.exe", L"realpopup.exe", L"soapbox.exe", L"syndicon.exe", L"tipicim.exe", L"transactim.exe",
        L"trillian.exe", L"trilogyec.exe", L"wannachat.exe", L"winmesgr.exe", L"winpopup.exe", L"yabber.exe",
        L"auvis.exe", L"vychat.exe", L"vm.exe", L"gyaber.exe", L"nostromo.exe", L"sim.exe",
        L"spark.exe", L"jajc.exe", L"rivalv3.exe", L"universe.exe", L"pexit.exe", L"rhymbox.exe",
        L"irjabber11.exe", L"messenger2.exe", L"rhombusim.exe", L"odigo.exe", L"qsr.exe", L"acacam.exe",
        L"record.exe", L"casmtasiastudio.exe", L"camrecorder.exe", L"camaudioeditor.exe", L"camplay.exe", L"camtheater.exe",
        L"cammenumaker.exe", L"captivate.exe", L"capsolut.exe", L"csplay.exe", L"csplaydx.exe", L"cskeeper.exe",
        L"cscamera.exe", L"cscamdx.exe", L"directset.exe", L"captureeye.exe", L"db.exe", L"democharge.exe",
        L"converter.exe", L"divx player.exe", L"iexplore.exe", L"dr.divx.exe", L"divx player.exe", L"escv.exe",
        L"escv2.exe", L"esr.exe", L"videocap.exe", L"frontcam.exe", L"courseware2.exe", L"sedit.exe",
        L"screenplay.exe", L"hycam2.exe", L"jing.exe", L"capture2.exe", L"wmenc.exe", L"wmeditor.exe",
        L"wmproedt.exe", L"wmstreamedt.exe", L"mediacamlt.exe", L"mediaplay.exe", L"mediacamav.exe", L"mediaplay.exe",
        L"robodemo.exe", L"screenminer.exe", L"sflash.exe", L"snemoplayer.exe", L"dxlock.exe", L"turbodemo.exe",
        L"winplayer.exe", L"winplayer.exe", L"wincam.exe", L"wincam.exe", L"capture.exe", L"spider.exe",
        L"capture.exe", L"scap.exe", L"scappro.exe", L"asc.exe", L"capture.exe", L"capture.exe",
        L"anycapture.exe", L"snapya!.exe", L"scrsmart.exe", L"bsscrcap.exe", L"captura.exe", L"cbg.exe",
        L"capexp.exe", L"cappro6.exe", L"capeze97.exe", L"czepro.exe", L"capture-it.exe", L"captureur.exe",
        L"capturewiz.exe", L"capturewiz.exe", L"capturex.exe", L"deskscan.exe", L"escrcap.exe", L"escr.exe",
        L"fscapture.exe", L"flash32.exe", L"frameshots.exe", L"frontlook.exe", L"fullshot.exe", L"printscreen.exe",
        L"grabber.exe", L"hotscrn.exe", L"hoversnap.exe", L"hprsnap6.exe", L"imagekeyrec.exe", L"jotsmart.exe",
        L"justscrn.exe", L"k-mania.exe", L"meazure.exe", L"mc.exe", L"mrcaptor.exe", L"mwsnap.exe",
        L"paint shop pro 9.exe", L"paint shop pro 9.exe", L"hprsnap.exe", L"print!.exe", L"pkey_pro.exe", L"prnscreen.exe",
        L"sb.exe", L"scm.exe", L"screengrab.exe", L"scrprt30.exe", L"ssm.exe", L"screengrab.exe",
        L"srip32.exe", L"screens.exe", L"sdcapture.exe", L"zoom.exe", L"scapture.exe", L"snagit32.exe",
        L"iexplore.exe", L"explorer.exe", L"spx.exe", L"sysdiag.exe", L"swbcap.exe", L"tnt_demo.exe",
        L"turbosnap.exe", L"ultrasnap.exe", L"usnappro.exe", L"wincpy70.exe", L"wincopy2006.exe", L"wink.exe",
        L"zoom.exe", L"zoomcap.exe", L"grabclipsave.exe", L"grabnmail10.exe", L"puush.exe", L"printkey2000.exe",
        L"hc.exe", L"rpcapd.exe", L"fiddler.exe", L"analyzer.exe", L"assniffer.exe", L"awpta.exe",
        L"billsniff.exe", L"cain.exe", L"abel.exe", L"capsa.exe", L"etherlook.exe", L"cv.exe",
        L"commra.exe", L"dasniffa.exe", L"dasniffa_svc.exe", L"dasniffb.exe", L"monitor.exe", L"agent.exe",
        L"etherd.exe", L"ethereal.exe", L"epeek.exe", L"ethersnoop.exe", L"framepad.exe", L"ehsniffer.exe",
        L"httptracer.exe", L"iptools.exe", L"ipmaster.exe", L"ipmasterpro.exe", L"iris.exe", L"irissvc.exe",
        L"lanhound.exe", L"isagent.exe", L"imagent.exe", L"netmon.exe", L"netcap.exe", L"mynetmon.exe",
        L"natas.exe", L"tsfnrs.exe", L"netresident.exe", L"netwox534.exe", L"ngrep.exe", L"ngssniff.exe",
        L"observer.exe", L"niprobe.exe", L"nirmonprobe.exe", L"pmon.exe", L"pvpro.exe", L"aps.exe",
        L"pcaptrace.exe", L"portpeeker.exe", L"proxytrace.exe", L"smsniff.exe", L"sniffem.exe", L"sniphere.exe",
        L"snort.exe", L"socspy32.exe", L"tcpspy.exe", L"tcpviewr.exe", L"tcptrace.exe", L"tpnet.exe",
        L"tpweb32.exe", L"tpwebpro.exe", L"tpedit.exe", L"tpwins32.exe", L"snifmon.exe", L"icqsnif.exe",
        L"usnfctr.exe", L"windump.exe", L"winsniff.exe", L"yatt.exe", L"iexplore.exe", L"httpsnoop.exe",
        L"nwr.exe", L"winacsr.exe", L"alogcfg.exe", L"alsys.exe", L"swatcher.exe", L"swsys.exe",
        L"allinonespy.exe", L"explorer.exe", L"explorer.exe", L"explorer.exe", L"explorer.exe", L"explorer.exe",
        L"cs2.exe", L"dbgview.exe", L"sysdiag.exe", L"svch0st.exe", L"estation.exe", L"esread.exe",
        L"usrsvcs.exe", L"filemon.exe", L"gdmgr.exe", L"gdadmin.exe", L"am.exe", L"logger.exe",
        L"la.exe", L"srvcks.exe", L"klp32.exe", L"ks.exe", L"no32mon.exe", L"iexplore.exe",
        L"sysdiag.exe", L"pcacmel.exe", L"pcacmes.exe", L"pcacmep.exe", L"viewer.exe", L"svchost.exe",
        L"svchoste.exe", L"procexp.exe", L"regmon.exe", L"main.exe", L"sysdiag.exe", L"spyanywhere.exe",
        L"sb32mon.exe", L"sspro.exe", L"svcwinra.exe", L"resfilter32.exe", L"tdimon.exe", L"tplus32.exe",
        L"wmsmod32.exe", L"iexplore.exe", L"svchost.exe", L"shadow32.exe", L"iexplore.exe", L"svchost.exe",
        L"logs viewer.exe", L"xpcspy.exe", L"explorer.exe", L"explorer.exe", L"multimon.exe", L"arc.exe",
        L"arm.exe", L"art.exe", L"regcleaner.exe", L"errordoctor.exe", L"errorkiller.exe", L"regcleaner.exe",
        L"jv16pt.exe", L"reg.exe", L"mmc.exe", L"regedit.exe", L"regedt32.exe", L"poledit.exe",
        L"ntperfec.exe", L"openedit.exe", L"pconpoint.exe", L"organizer.exe", L"regcure.exe", L"regeditr.exe",
        L"reghance.exe", L"rrc.exe", L"rr.exe", L"ranalyst.exe", L"rcscheduler.exe", L"regcmd.exe",
        L"rcrawler.exe", L"regdrill.exe", L"explorer.exe", L"rfagent.exe", L"reg1aid.exe", L"registryfix.exe",
        L"regjump.exe", L"regmech.exe", L"regmedic.exe", L"regtool.exe", L"trashreg.exe", L"rc.exe",
        L"regwatch.exe", L"regworkshop.exe", L"rpadmin.exe", L"regprot.exe", L"regmon.exe", L"regrestore.exe",
        L"regrun2.exe", L"regace.exe", L"procman.exe", L"regseeker.exe", L"regshot.exe", L"regsnap.exe",
        L"regsupreme.exe", L"dllhost.exe", L"regrepair.exe", L"tracker.exe", L"integrator.exe", L"regcleaner.exe",
        L"wcwservice.exe", L"wcreporter.exe", L"wcwindows.exe", L"issexplorer.exe", L"zenkey.exe", L"winroll.exe",
        L"vitrite.exe", L"tweakwin.exe", L"transwin.exe", L"transpapps.exe", L"winhider.exe", L"quick shell.exe",
        L"powermenu.exe", L"transparent.exe", L"hidewindow.exe", L"glass2k.exe", L"connectaddin.exe", L"pronto.exe",
        L"blackboardim.exe", L"ymsgr_~1.exe", L"conf.exe", L"msnmsgr.exe", L"ventrilo.exe", L"vbuzzer.exe",
        L"trillian.exe", L"teamspeak.exe", L"skype.exe", L"iexplore.exe", L"roger.exe", L"qphone.exe",
        L"pctel.exe", L"commctr.exe", L"mandolino3.3.exe", L"phoenix2.4.exe", L"icqlite.exe", L"pcphone.exe",
        L"googletalk.exe", L"gecko phone.exe", L"talk.exe", L"dpcham.exe", L"dpcham.exe", L"buddytalk.exe",
        L"aim6.exe", L"dialer.exe", L"zohomeeting.exe", L"sharedview.exe", L"communicator.exe", L"pdnotes.exe",
        L"cnotes.exe", L"cnotes.exe", L"winpinapp.exe", L"winpinapp.exe", L"topdesk.exe", L"deskspace.exe",
        L"yodm3d.exe", L"madotate.exe", L"objectdock.exe", L"dock64.exe", L"rocketdock.exe", L"delldock.exe",
        L"googledesktop.exe", L"outlook.exe", L"outlook.exe", L"ruby.exe", L"rubyw.exe", L"pgservice.exe",
        L"pg_service_launcher.exe", L"pg_tray.exe", L"motioncontrol.exe", L"pg.exe", L"pg_osd.exe", L"pg_settingsapp.exe",
        L"pg_sdk_devapp.vs11.exe", L"webcamsplitterserver.exe", L"pg_logon.exe", L"motioncontrolui.exe", L"trayctrlnotify.exe", L"cammute.exe",
        L"commmain.exe", L"commosd.exe", L"snapshot.exe", L"tpfnf6.exe", L"tpknrres.exe", L"tpknrsvc.exe",
        L"hpmediasmartwebcam.exe", L"ycmmirage.exe", L"taskschedulerex.exe", L"webcam.exe", L"muistartmenu.exe", L"netflix.exe",
        L"rainlendar2.exe", L"ditto.exe", L"fscapture.exe", L"fscrosshair.exe", L"fsrecorder.exe", L"phraseexpress.exe",
        L"pexinst.exe", L"autohotkey.exe", L"au3_spy.exe", L"autoscriptwriter.exe", L"cucore.exe", L"confagent.exe",
        L"caxhost.exe", L"onenoteim.exe", L"evernotemetro.exe", L"vircam.exe", L"vircamws.exe", L"lskhelper.exe",
        L"lskhlpr64.exe", L"lsk_run.exe", L"lsklremv.exe", L"student.exe", L"spotify.exe", L"spotifycrashservice.exe",
        L"spotifylauncher.exe", L"spotifywebhelper.exe", L"wow_helper.exe", L"steam.exe", L"steamerrorreporter.exe", L"steamerrorreporter64.exe",
        L"steamservice.exe", L"steamwebhelper.exe", L"gameoverlayui.exe", L"streaming_client.exe", L"writeminidump.exe", L"x64launcher.exe",
        L"x86launcher.exe", L"droidcamapp.exe", L"abelcam.exe", L"abelcamupdater.exe", L"abelsupport.exe", L"abelsvc.exe",
        L"arcsendmail.exe", L"asdownloader.exe", L"umcedvdplayer.exe", L"utility.exe", L"aswarasr.exe", L"stikynot.exe",
        L"ciscojabber.exe", L"ciscojabberprt.exe", L"jabbervideo.exe", L"jabber.exe", L"g2mvideoconference.exe", L"g2mui.exe",
        L"youcam.exe", L"youcamservice.exe", L"youcam2.exe", L"youcamservice2.exe", L"youcam3.exe", L"youcamservice3.exe",
        L"youcam4.exe", L"youcamservice4.exe", L"youcam5.exe", L"youcamservice5.exe", L"youcam6.exe", L"youcamservice6.exe",
        L"youcam7.exe", L"youcamservice7.exe", L"youcam8.exe", L"youcamservice8.exe", L"youcam9.exe", L"youcamservice9.exe",
        L"youcam10.exe", L"youcamservice10.exe", L"youcam11.exe", L"youcamservice11.exe", L"always-on-top.exe", L"messagingapplication.exe",
        L"lmi_rescue.exe", L"dellclientsystemupdate.exe", L"discord.exe", L"shtctky.exe", L"telegram.exe", L"airparrot.exe",
        L"airparrot2.exe", L"airparrot3.exe", L"airparrot4.exe", L"airparrot5.exe", L"screenshotcaptor.exe", L"dexpot.exe",
        L"dexpot64.exe", L"video.ui.exe", L"fraps.exe", L"obs.exe", L"overwolf.exe", L"overwolfbrowser.exe",
        L"overwolfhelper.exe", L"overwolfstore.exe", L"evolveclient.exe", L"evolveui.exe", L"gameshow.exe", L"wirecast.exe",
        L"powerpnt.exe", L"msosrec.exe", L"mumble.exe", L"slack.exe", L"telegram.exe", L"psr.exe",
        L"rfusclient.exe", L"rutview.exe", L"rutserv.exe", L"groupmeuwa.exe", L"hxcalendarappimm.exe", L"obs64.exe",
        L"obs32.exe", L"windowsshoppingapp.exe", L"windowsshoppingapp.exe", L"launchy.exe", L"wox.exe", L"teams.exe",
        L"hipchat.exe", L"screenconnect.windowsclient.exe", L"hxoutlook.exe", L"hxtsr.exe", L"vncagent.exe", L"vncserver.exe",
        L"vncserverui.exe", L"vncviewer.exe", L"gystation.exe", L"gyazowin.exe", L"gyazogif.exe", L"gyonboarding.exe",
        L"recorder.exe", L"quickshot.exe", L"record.exe", L"debut.exe", L"acethinker screen grabber pro.exe", L"apowersoft screen recorder pro 2.exe",
        L"fseditor.exe", L"fsrecorder.exe", L"fssplash.exe", L"filmora.exe", L"screencapture.exe", L"pushbullet_client.exe",
        L"pushbullet_watchdog.exe", L"anydesk.exe", L"autohotkeya32.exe", L"autohotkeyu32.exe", L"autohotkeyu64.exe", L"listary.exe",
        L"nimbus capture.exe", L"sharex.exe", L"xsplit.core.exe", L"xsplit.xbcbp.exe", L"xsplit.gamecaster.exe", L"xsplit.xgcbp.exe",
        L"displayfusionhookapp32.exe", L"displayfusionsettings.exe", L"keybreeze.exe", L"findandrunrobot.exe", L"everything.exe", L"keypirinha.exe",
        L"keypirinha-x86.exe", L"keypirinha-x64.exe", L"bdcam.exe", L"sbiesvc.exe", L"sandboxiecrypto.exe", L"sandboxiebits.exe",
        L"sbiectrl.exe", L"obs32.exe", L"obs64.exe", L"nvidia geforce experience.exe", L"nvidia share.exe", L"nvsphelper.exe",
        L"nvsphelper64.exe", L"nvdisplay.container.exe", L"nvcontainer.exe", L"nvidia web helper.exe", L"kaltura capture.exe", L"logicapture.exe",
        L"gamebar.exe", L"gamebarft.exe", L"gamebarftserver.exe", L"screenrecorder.exe", L"freeonlinescreenrecorder.exe", L"chime.exe",
        L"whatsapp.exe", L"dtaskmanagerportable.exe", L"kakaotalk.exe", L"mdrserv.exe", L"cmd.exe", L"powershell.exe",
        L"twitter-win8.exe", L"deskpins.exe", L"displayfusion.exe", L"displayfusionhookappwin6064.exe", L"displayfusionhookappwin6032.exe", L"displayfusionservice.exe",
        L"desktops.exe", L"synergy.exe", L"synergyc.exe", L"synergyd.exe", L"synergys.exe", L"taskmgr.exe",
        L"sidebar.exe", L"sidebar.exe", L"avgas.exe", L"smartboardtools.exe", L"smartboardservice.exe", L"helppane.exe",
        L"wwahost.exe", L"glass2k.exe", L"truetransparency.exe", L"manycam.exe", L"magiccamera.exe", L"ctlvcentral3.exe",
        L"ctlvcentral2.exe", L"ctlvcentral.exe", L"webcamdell.exe", L"webcamdell2.exe", L"remote_assistance_host.exe", L"remoting_native_messaging_host.exe",
        L"remoting_desktop.exe", L"apc_admin.exe", L"apc_host.exe", L"apc_admin.exe", L"apc_host.exe", L"conf.exe",
        L"mnmsrvc.exe", L"mstsc.exe", L"netctl.exe", L"netctl.exe", L"netserv.exe", L"netserv.exe",
        L"ncscc.exe", L"ncscc.exe", L"netchat.exe", L"netchat.exe", L"vncviewer.exe", L"winvnc.exe",
        L"winvnc4.exe", L"vncviewer.exe", L"rcpserver.exe", L"rcpadmin.exe", L"rpaccess.exe", L"rpaccesshs.exe",
        L"actionsserver.exe", L"tvnserver.exe", L"tvnviewer.exe", L"vncviewer.exe", L"winvnc.exe", L"vncviewer.exe",
        L"winvnc.exe", L"vncviewer.exe", L"win2vnc.exe", L"sshdctrl.exe", L"winsshd.exe", L"keygen.exe",
        L"wissh.exe", L"g2svc.exe", L"g2comm.exe", L"g2tray.exe", L"g2pre.exe", L"logmein.exe",
        L"ramaint.exe", L"join.me.exe", L"logmein.exe", L"teamviewer.exe", L"teamviewer.exe", L"teamviewer.exe",
        L"romserver.exe", L"romserver.exe", L"rserver3.exe", L"rserver3.exe", L"igremote.exe", L"igremote.exe",
        L"rpcsetup.exe", L"rpcgrab.exe", L"rpcsetup.exe", L"crossloopconnect.exe", L"crossloopservice.exe", L"crossloopservice.exe",
        L"yuuguu.exe", L"srserver.exe", L"srservice.exe", L"srsoobe.exe", L"altdesk.exe", L"bosskey.exe",
        L"virtdesktop.exe", L"cdesk.exe", L"dp.exe", L"exedesk.exe", L"exedesk_wd.exe", L"goscreen.exe",
        L"litestep.exe", L"managedesk.exe", L"mud2004.exe", L"multidesk.exe", L"desktop.exe", L"pictowin.exe",
        L"talisman.exe", L"vern36.exe", L"vdtlbx.exe", L"kauths.exe", L"virtuawin.exe", L"winlist.exe",
        L"explorer.exe", L"winspace.exe", L"xdesk.exe", L"ultramon.exe", L"aceclient.exe", L"acemessage.exe",
        L"run.exe", L"aim6.exe", L"ayttm.exe", L"bitwise.exe", L"clique2.exe", L"exodus.exe",
        L"gabber.exe", L"gaim.exe", L"gajim.exe", L"gcn.exe", L"goim.exe", L"gush.exe",
        L"gushui.exe", L"hello.exe", L"icqlite.exe", L"igoinc~1.exe", L"messenger2.exe", L"im2wizard.exe",
        L"imvite.exe", L"ima.exe", L"imc.exe", L"ims.exe", L"instant.exe", L"messenger.exe",
        L"igc.exe", L"kava.exe", L"linq.exe", L"lluna.exe", L"maxxchat.exe", L"miranda32.exe",
        L"mirc.exe", L"msnmsgr.exe", L"myjabber.exe", L"neos.exe", L"officepopup.exe", L"paltalk.exe",
        L"pandion.exe", L"papla.exe", L"pidgin.exe", L"lync.exe", L"winvmaclient.exe", L"psi.exe",
        L"realpopup.exe", L"soapbox.exe", L"syndicon.exe", L"tipicim.exe", L"transactim.exe", L"trillian.exe",
        L"trilogyec.exe", L"wannachat.exe", L"winmesgr.exe", L"winpopup.exe", L"yabber.exe", L"auvis.exe",
        L"vychat.exe", L"vm.exe", L"gyaber.exe", L"nostromo.exe", L"sim.exe", L"spark.exe",
        L"jajc.exe", L"rivalv3.exe", L"universe.exe", L"pexit.exe", L"rhymbox.exe", L"irjabber11.exe",
        L"messenger2.exe", L"rhombusim.exe", L"odigo.exe", L"qsr.exe", L"acacam.exe", L"record.exe",
        L"casmtasiastudio.exe", L"camrecorder.exe", L"camaudioeditor.exe", L"camplay.exe", L"camtheater.exe", L"cammenumaker.exe",
        L"captivate.exe", L"capsolut.exe", L"csplay.exe", L"csplaydx.exe", L"cskeeper.exe", L"cscamera.exe",
        L"cscamdx.exe", L"directset.exe", L"captureeye.exe", L"db.exe", L"democharge.exe", L"converter.exe",
        L"divx player.exe", L"iexplore.exe", L"dr.divx.exe", L"divx player.exe", L"escv.exe", L"escv2.exe",
        L"esr.exe", L"videocap.exe", L"fraps.exe", L"frontcam.exe", L"courseware2.exe", L"sedit.exe",
        L"screenplay.exe", L"hycam2.exe", L"jing.exe", L"capture2.exe", L"wmenc.exe", L"wmeditor.exe",
        L"wmproedt.exe", L"wmstreamedt.exe", L"mediacamlt.exe", L"mediaplay.exe", L"mediacamav.exe", L"mediaplay.exe",
        L"robodemo.exe", L"screenminer.exe", L"sflash.exe", L"snemoplayer.exe", L"dxlock.exe", L"turbodemo.exe",
        L"winplayer.exe", L"winplayer.exe", L"wincam.exe", L"wincam.exe", L"capture.exe", L"spider.exe",
        L"capture.exe", L"scap.exe", L"scappro.exe", L"asc.exe", L"capture.exe", L"capture.exe",
        L"anycapture.exe", L"snapya!.exe", L"scrsmart.exe", L"bsscrcap.exe", L"captura.exe", L"cbg.exe",
        L"capexp.exe", L"cappro6.exe", L"capeze97.exe", L"czepro.exe", L"capture-it.exe", L"captureur.exe",
        L"capturewiz.exe", L"capturewiz.exe", L"capturex.exe", L"deskscan.exe", L"escrcap.exe", L"escr.exe",
        L"fscapture.exe", L"flash32.exe", L"frameshots.exe", L"frontlook.exe", L"fullshot.exe", L"printscreen.exe",
        L"grabber.exe", L"hotscrn.exe", L"hoversnap.exe", L"hprsnap6.exe", L"imagekeyrec.exe", L"jotsmart.exe",
        L"justscrn.exe", L"k-mania.exe", L"meazure.exe", L"mc.exe", L"mrcaptor.exe", L"mwsnap.exe",
        L"paint shop pro 9.exe", L"paint shop pro 9.exe", L"hprsnap.exe", L"print!.exe", L"pkey_pro.exe", L"prnscreen.exe",
        L"sb.exe", L"scm.exe", L"screengrab.exe", L"scrprt30.exe", L"ssm.exe", L"screengrab.exe",
        L"srip32.exe", L"screens.exe", L"sdcapture.exe", L"zoom.exe", L"scapture.exe", L"snagit32.exe",
        L"iexplore.exe", L"explorer.exe", L"spx.exe", L"sysdiag.exe", L"swbcap.exe", L"tnt_demo.exe",
        L"turbosnap.exe", L"ultrasnap.exe", L"usnappro.exe", L"wincpy70.exe", L"wincopy2006.exe", L"wink.exe",
        L"zoom.exe", L"zoomcap.exe", L"grabclipsave.exe", L"grabnmail10.exe", L"puush.exe", L"printkey2000.exe",
        L"hc.exe", L"rpcapd.exe", L"fiddler.exe", L"analyzer.exe", L"assniffer.exe", L"awpta.exe",
        L"billsniff.exe", L"cain.exe", L"abel.exe", L"capsa.exe", L"etherlook.exe", L"cv.exe",
        L"commra.exe", L"dasniffa.exe", L"dasniffa_svc.exe", L"dasniffb.exe", L"monitor.exe", L"agent.exe",
        L"etherd.exe", L"ethereal.exe", L"epeek.exe", L"ethersnoop.exe", L"framepad.exe", L"ehsniffer.exe",
        L"httptracer.exe", L"iptools.exe", L"ipmaster.exe", L"ipmasterpro.exe", L"iris.exe", L"irissvc.exe",
        L"lanhound.exe", L"isagent.exe", L"imagent.exe", L"netmon.exe", L"netcap.exe", L"mynetmon.exe",
        L"natas.exe", L"tsfnrs.exe", L"netresident.exe", L"netwox534.exe", L"ngrep.exe", L"ngssniff.exe",
        L"observer.exe", L"niprobe.exe", L"nirmonprobe.exe", L"pmon.exe", L"pvpro.exe", L"aps.exe",
        L"pcaptrace.exe", L"portpeeker.exe", L"proxytrace.exe", L"smsniff.exe", L"sniffem.exe", L"sniphere.exe",
        L"snort.exe", L"socspy32.exe", L"tcpspy.exe", L"tcpviewr.exe", L"tcptrace.exe", L"tpnet.exe",
        L"tpweb32.exe", L"tpwebpro.exe", L"tpedit.exe", L"tpwins32.exe", L"snifmon.exe", L"icqsnif.exe",
        L"usnfctr.exe", L"windump.exe", L"winsniff.exe", L"yatt.exe", L"iexplore.exe", L"httpsnoop.exe",
        L"nwr.exe", L"winacsr.exe", L"alogcfg.exe", L"alsys.exe", L"swatcher.exe", L"swsys.exe",
        L"allinonespy.exe", L"explorer.exe", L"explorer.exe", L"explorer.exe", L"explorer.exe", L"explorer.exe",
        L"cs2.exe", L"dbgview.exe", L"sysdiag.exe", L"svch0st.exe", L"estation.exe", L"esread.exe",
        L"usrsvcs.exe", L"filemon.exe", L"gdmgr.exe", L"gdadmin.exe", L"am.exe", L"logger.exe",
        L"la.exe", L"srvcks.exe", L"klp32.exe", L"ks.exe", L"no32mon.exe", L"iexplore.exe",
        L"sysdiag.exe", L"pcacmel.exe", L"pcacmes.exe", L"pcacmep.exe", L"viewer.exe", L"svchost.exe",
        L"svchoste.exe", L"procexp.exe", L"regmon.exe", L"main.exe", L"sysdiag.exe", L"spyanywhere.exe",
        L"sb32mon.exe", L"sspro.exe", L"svcwinra.exe", L"resfilter32.exe", L"tdimon.exe", L"tplus32.exe",
        L"wmsmod32.exe", L"iexplore.exe", L"svchost.exe", L"shadow32.exe", L"iexplore.exe", L"svchost.exe",
        L"logs viewer.exe", L"xpcspy.exe", L"explorer.exe", L"explorer.exe", L"multimon.exe", L"arc.exe",
        L"arm.exe", L"art.exe", L"regcleaner.exe", L"errordoctor.exe", L"errorkiller.exe", L"regcleaner.exe",
        L"jv16pt.exe", L"reg.exe", L"mmc.exe", L"regedit.exe", L"regedt32.exe", L"poledit.exe",
        L"ntperfec.exe", L"openedit.exe", L"pconpoint.exe", L"organizer.exe", L"regcure.exe", L"regeditr.exe",
        L"reghance.exe", L"rrc.exe", L"rr.exe", L"ranalyst.exe", L"rcscheduler.exe", L"regcmd.exe",
        L"rcrawler.exe", L"regdrill.exe", L"explorer.exe", L"rfagent.exe", L"reg1aid.exe", L"registryfix.exe",
        L"regjump.exe", L"regmech.exe", L"regmedic.exe", L"regtool.exe", L"trashreg.exe", L"rc.exe",
        L"regwatch.exe", L"regworkshop.exe", L"rpadmin.exe", L"regprot.exe", L"regmon.exe", L"regrestore.exe",
        L"regrun2.exe", L"regace.exe", L"procman.exe", L"regseeker.exe", L"regshot.exe", L"regsnap.exe",
        L"regsupreme.exe", L"dllhost.exe", L"regrepair.exe", L"tracker.exe", L"integrator.exe", L"regcleaner.exe",
        L"wcwservice.exe", L"wcreporter.exe", L"wcwindows.exe", L"issexplorer.exe", L"zenkey.exe", L"winroll.exe",
        L"vitrite.exe", L"tweakwin.exe", L"transwin.exe", L"transpapps.exe", L"winhider.exe", L"quick shell.exe",
        L"powermenu.exe", L"transparent.exe", L"hidewindow.exe", L"glass2k.exe", L"connectaddin.exe", L"pronto.exe",
        L"blackboardim.exe", L"ymsgr_~1.exe", L"conf.exe", L"msnmsgr.exe", L"ventrilo.exe", L"vbuzzer.exe",
        L"trillian.exe", L"teamspeak.exe", L"skype.exe", L"iexplore.exe", L"roger.exe", L"qphone.exe",
        L"pctel.exe", L"commctr.exe", L"mandolino3.3.exe", L"phoenix2.4.exe", L"icqlite.exe", L"pcphone.exe",
        L"googletalk.exe", L"gecko phone.exe", L"talk.exe", L"dpcham.exe", L"dpcham.exe", L"buddytalk.exe",
        L"aim6.exe", L"dialer.exe", L"zohomeeting.exe", L"sharedview.exe", L"communicator.exe", L"pdnotes.exe",
        L"cnotes.exe", L"cnotes.exe", L"winpinapp.exe", L"winpinapp.exe", L"topdesk.exe", L"deskspace.exe",
        L"yodm3d.exe", L"madotate.exe", L"objectdock.exe", L"dock64.exe", L"rocketdock.exe", L"delldock.exe",
        L"googledesktop.exe", L"ruby.exe", L"rubyw.exe", L"pgservice.exe", L"pg_service_launcher.exe", L"pg_tray.exe",
        L"motioncontrol.exe", L"pg.exe", L"pg_osd.exe", L"pg_settingsapp.exe", L"pg_sdk_devapp.vs11.exe", L"webcamsplitterserver.exe",
        L"pg_logon.exe", L"motioncontrolui.exe", L"cucore.exe", L"confagent.exe", L"caxhost.exe", L"aswarasr.exe",
        L"vircam.exe", L"vircamws.exe", L"stikynot.exe", L"ciscojabber.exe", L"ciscojabberprt.exe", L"jabbervideo.exe",
        L"jabber.exe", L"g2mvideoconference.exe", L"g2mui.exe", L"youcam.exe", L"youcamservice.exe", L"youcam2.exe",
        L"youcamservice2.exe", L"youcam3.exe", L"youcamservice3.exe", L"youcam4.exe", L"youcamservice4.exe", L"youcam5.exe",
        L"youcamservice5.exe", L"youcam6.exe", L"youcamservice6.exe", L"youcam7.exe", L"youcamservice7.exe", L"youcam8.exe",
        L"youcamservice8.exe", L"youcam9.exe", L"youcamservice9.exe", L"youcam10.exe", L"youcamservice10.exe", L"youcam11.exe",
        L"youcamservice11.exe", L"always-on-top.exe", L"messagingapplication.exe", L"lmi_rescue.exe", L"dellclientsystemupdate.exe", L"discord.exe",
        L"shtctky.exe", L"telegram.exe", L"airparrot.exe", L"airparrot2.exe", L"airparrot3.exe", L"airparrot4.exe",
        L"airparrot5.exe", L"screenshotcaptor.exe", L"dexpot.exe", L"dexpot64.exe", L"video.ui.exe", L"fraps.exe",
        L"obs.exe", L"overwolf.exe", L"overwolfbrowser.exe", L"overwolfhelper.exe", L"overwolfstore.exe", L"evolveclient.exe",
        L"evolveui.exe", L"gameshow.exe", L"wirecast.exe", L"powerpnt.exe", L"msosrec.exe", L"mumble.exe",
        L"slack.exe", L"telegram.exe", L"psr.exe", L"rfusclient.exe", L"rutview.exe", L"rutserv.exe",
        L"groupmeuwa.exe", L"hxcalendarappimm.exe", L"obs64.exe", L"obs32.exe", L"windowsshoppingapp.exe", L"windowsshoppingapp.exe",
        L"launchy.exe", L"wox.exe", L"teams.exe", L"hipchat.exe", L"screenconnect.windowsclient.exe", L"hxoutlook.exe",
        L"hxtsr.exe", L"vncagent.exe", L"vncserver.exe", L"vncserverui.exe", L"vncviewer.exe", L"sbiesvc.exe",
        L"sandboxiecrypto.exe", L"sandboxiebits.exe", L"gystation.exe", L"gyazowin.exe", L"gyazogif.exe", L"gyonboarding.exe",
        L"recorder.exe", L"quickshot.exe", L"record.exe", L"debut.exe", L"acethinker screen grabber pro.exe", L"apowersoft screen recorder pro 2.exe",
        L"fseditor.exe", L"fsrecorder.exe", L"fssplash.exe", L"filmora.exe", L"screencapture.exe", L"pushbullet_client.exe",
        L"pushbullet_watchdog.exe", L"anydesk.exe", L"autohotkeya32.exe", L"autohotkeyu32.exe", L"autohotkeyu64.exe", L"listary.exe",
        L"nimbus capture.exe", L"sharex.exe", L"xsplit.core.exe", L"xsplit.xbcbp.exe", L"xsplit.gamecaster.exe", L"xsplit.xgcbp.exe",
        L"displayfusionhookapp32.exe", L"displayfusionsettings.exe", L"keybreeze.exe", L"findandrunrobot.exe", L"everything.exe", L"keypirinha.exe",
        L"keypirinha-x86.exe", L"keypirinha-x64.exe", L"bdcam.exe", L"obs32.exe", L"obs64.exe", L"nvidia geforce experience.exe",
        L"nvidia share.exe", L"nvsphelper.exe", L"nvsphelper64.exe", L"nvdisplay.container.exe", L"nvcontainer.exe", L"nvidia web helper.exe",
        L"kaltura capture.exe", L"logicapture.exe", L"gamebar.exe", L"gamebarft.exe", L"gamebarftserver.exe", L"screenrecorder.exe",
        L"freeonlinescreenrecorder.exe", L"chime.exe", L"whatsapp.exe", L"dtaskmanagerportable.exe", L"kakaotalk.exe", L"mdrserv.exe" };
}
